services: 
  proxy: 
    build:
      context: nginx
    container_name: nginx 
    ports:
      - "80:80"
    restart: always 
    networks:
      - node-network
  app:
    build:
      context: .
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node app.js
    restart: always
    volumes:
      - vol-node:/root
    networks: 
      - node-network
    tty: true
    ports: 
      - "3000:3000"
    depends_on: 
       - db
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - vol-db:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge   
volumes:
  vol-node:
  vol-db: